"""
Stage 2 — Preprocessing
========================
Cleans the raw text extracted in Stage 1: fixes PDF extraction
artifacts, strips publisher front matter, normalizes document
structure and reports before/after statistics.
"""

import os
import re
import json

import numpy as np

DATA_DIR = "data"


# ==================================================
# Fix PDF Broken Words
# ==================================================

def fix_pdf_broken_words(text):
    """
    Fix common PDF extraction artifacts.
    Only fixes known broken words. Does NOT merge normal words.
    """

    replacements = {
        "fi rst": "first",
        "Fi rst": "First",
        "defi brillator": "defibrillator",
        "Defi brillator": "Defibrillator",
        "cardio pulmonary": "cardiopulmonary",
        "blood- borne": "blood-borne",
        "fi rst-aid": "first-aid",
        "emergency scene": "emergency scene",
    }

    for wrong, correct in replacements.items():
        text = text.replace(wrong, correct)

    return text


# ==================================================
# Document Cleaning Pipeline
# ==================================================

def clean_document(text):
    """
    Cleaning pipeline for Docling output.
    Removes PDF artifacts while preserving structure.
    """

    # 1. Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # 2. Join hyphenated words split across lines
    text = re.sub(r'(\w+)-\s*\n\s*(\w+)', r'\1\2', text)

    # 3. Fix known PDF broken words
    text = fix_pdf_broken_words(text)

    # 4. Remove HTML comments generated by Docling
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)

    # 5. Remove URLs
    text = re.sub(r'https?://\S+', '', text)

    # 6. Remove emails
    text = re.sub(r'\S+@\S+', '', text)

    # 7. Remove publisher/license artifacts
    license_patterns = [
        r'Downloaded from.*',
        r'See the Terms and Conditions.*',
        r'OA articles are governed by.*',
    ]
    for p in license_patterns:
        text = re.sub(p, '', text, flags=re.IGNORECASE)

    # 8. Remove standalone page numbers
    text = re.sub(r'(?m)^\s*\d+\s*$', '', text)

    # 9. Remove isolated Roman numerals
    text = re.sub(r'(?m)^\s*[IVXLCDMivxlcdm]+\s*$', '', text)

    # 10. Normalize spaces
    text = re.sub(r'[ \t]+', ' ', text)

    # 11. Remove spaces before newline
    text = re.sub(r'[ \t]+\n', '\n', text)

    # 12. Collapse blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


# ==================================================
# Remove Publisher Front Matter
# ==================================================
# The First Aid Reference Guide has ~11 pages of cover, funding
# acknowledgement, copyright/ISBN, medical advisory group bios,
# disclaimer, emergency contact card and Table of Contents before the
# real content starts. Chapter 1 opens with a reliable, book-specific
# anchor heading.

def remove_front_matter(text):
    """
    Remove publisher front matter. Keep content starting from Chapter 1.
    """

    start_pattern = r"#+\s*Chapter\s+1\s+Introduction\s+to\s+First\s+Aid"

    match = re.search(start_pattern, text, flags=re.IGNORECASE)

    if match:
        text = text[match.start():]

    return text.strip()


# ==================================================
# Structure Normalization
# ==================================================

def normalize_structure(text, headings=None):
    """
    Normalize document structure for RAG.

    - Fixes spacing after hyphens.
    - Separates merged headings from previous text.
    - Removes duplicate consecutive lines.
    - Normalizes whitespace.
    """

    # 1. Fix missing spaces after hyphens
    text = re.sub(r'-(?=[A-Za-z])', '- ', text)

    # 2. Restore headings merged into previous sentence
    if headings:
        headings = sorted(headings, key=len, reverse=True)

        for heading in headings:
            heading = heading.strip()
            if not heading:
                continue

            pattern = r'(?<!\n)' + re.escape(" " + heading)
            text = re.sub(pattern, f"\n\n## {heading}", text)

    # 3. Remove duplicated consecutive lines
    cleaned_lines = []
    previous = ""

    for line in text.splitlines():
        line = line.strip()

        if not line:
            cleaned_lines.append("")
            previous = ""
            continue

        if line == previous:
            continue

        cleaned_lines.append(line)
        previous = line

    text = "\n".join(cleaned_lines)

    # 4. Normalize spaces
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


# ==================================================
# Document Statistics
# ==================================================

def compute_document_statistics(text_items):

    word_counts = [len(item.split()) for item in text_items if item.strip()]

    return {
        "num_text_items": len(text_items),
        "total_words": int(sum(word_counts)),
        "total_chars": int(sum(len(item) for item in text_items)),
        "avg_words_per_item": round(float(np.mean(word_counts)), 1) if word_counts else 0,
        "median_words_per_item": round(float(np.median(word_counts)), 1) if word_counts else 0,
        "min_words_per_item": int(min(word_counts)) if word_counts else 0,
        "max_words_per_item": int(max(word_counts)) if word_counts else 0,
        "items_low_content": int(sum(1 for wc in word_counts if wc < 20)),
    }


def compare_before_after(raw_items, cleaned_items):

    before_words = sum(len(item.split()) for item in raw_items if item.strip())
    after_words = sum(len(item.split()) for item in cleaned_items if item.strip())

    print("=" * 50)
    print("CLEANING SUMMARY")
    print("=" * 50)
    print(f"Words Before Cleaning : {before_words:,}")
    print(f"Words After Cleaning  : {after_words:,}")
    print(f"Removed Words         : {before_words - after_words:,}")

    if before_words > 0:
        print(f"Retention Rate        : {(after_words / before_words) * 100:.2f}%")


# ==================================================
# Run Preprocessing
# ==================================================

if __name__ == "__main__":

    with open(os.path.join(DATA_DIR, "raw_text.txt"), "r", encoding="utf-8") as f:
        raw_text = f.read()

    with open(os.path.join(DATA_DIR, "headings.json"), "r", encoding="utf-8") as f:
        headings = json.load(f)

    # Cleaning -> front matter removal -> structure normalization
    cleaned_text = clean_document(raw_text)
    cleaned_text = remove_front_matter(cleaned_text)
    cleaned_text = normalize_structure(cleaned_text, headings=headings)

    with open(os.path.join(DATA_DIR, "cleaned_text.txt"), "w", encoding="utf-8") as f:
        f.write(cleaned_text)

    # Statistics on the raw paragraphs vs. cleaned paragraphs
    raw_items = raw_text.split("\n\n")
    cleaned_items = [clean_document(item) for item in raw_items]

    stats = compute_document_statistics(raw_items)

    print("=" * 50)
    print("DOCUMENT STATISTICS")
    print("=" * 50)
    for key, value in stats.items():
        print(f"{key:<30}: {value}")

    print()
    compare_before_after(raw_items, cleaned_items)

    print("\n" + "=" * 60)
    print("DOCUMENT PREVIEW (AFTER CLEANING)")
    print("=" * 60)
    print(cleaned_text[:2000])
