"""
Streamlit App — First Aid RAG Assistant
========================================
Loads the persisted indexes built by stages 01-05 and serves an
interactive bilingual (Arabic/English) first-aid Q&A assistant built
on the hybrid retrieval + cross-encoder reranking + grounded LLM
pipeline from stages 06-07.

Run with:
    streamlit run streamlit_app.py
"""

import os
import pickle

import numpy as np
import pandas as pd
import streamlit as st
from sentence_transformers import SentenceTransformer

import importlib

retrieve_context_module = importlib.import_module("06_retrieve_context")
prompting_module = importlib.import_module("07_prompting")

DATA_DIR = "data"
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

REQUIRED_FILES = [
    "chunks.csv",
    "tfidf_index.pkl",
    "bm25_index.pkl",
    "embedding_matrix.npy",
]


def check_data_files():
    """Returns the list of required data/ files that are missing."""
    missing = []
    for filename in REQUIRED_FILES:
        path = os.path.join(DATA_DIR, filename)
        if not os.path.exists(path):
            missing.append(path)
    return missing


@st.cache_resource(show_spinner="Loading knowledge base...")
def load_pipeline_resources():

    chunks_df = pd.read_csv(os.path.join(DATA_DIR, "chunks.csv"), encoding="utf-8-sig")

    with open(os.path.join(DATA_DIR, "tfidf_index.pkl"), "rb") as f:
        tfidf_bundle = pickle.load(f)

    with open(os.path.join(DATA_DIR, "bm25_index.pkl"), "rb") as f:
        bm25 = pickle.load(f)

    embedding_matrix = np.load(os.path.join(DATA_DIR, "embedding_matrix.npy"))
    embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)

    return {
        "chunks_df": chunks_df,
        "tfidf_vectorizer": tfidf_bundle["vectorizer"],
        "tfidf_matrix": tfidf_bundle["matrix"],
        "bm25": bm25,
        "embedding_model": embedding_model,
        "embedding_matrix": embedding_matrix,
    }


def main():

    st.set_page_config(page_title="First Aid RAG Assistant", page_icon="🩹")

    st.title("🩹 First Aid Reference Guide — RAG Assistant")
    st.caption("St. John Ambulance Canada — First Aid Reference Guide, 4th Edition")

    missing_files = check_data_files()
    if missing_files:
        st.error(
            "The knowledge base files are missing, so the app can't start.\n\n"
            "Missing:\n"
            + "\n".join(f"- `{path}`" for path in missing_files)
            + "\n\n"
            "These are generated by running `01_documents.py` through "
            "`04_vector_representation.py` locally, and must be committed "
            "to the repo under `data/` (they are **not** produced automatically "
            "on Streamlit Cloud). Check `.gitignore` doesn't exclude `data/`."
        )
        st.stop()

    resources = load_pipeline_resources()

    st.info(
        "Note: answer generation calls a local Ollama server "
        "(`http://localhost:11434`). This works when running the app on "
        "your own machine with Ollama installed, but Streamlit Cloud has "
        "no access to it — generation will fail there unless Ollama is "
        "swapped for a hosted LLM API.",
        icon="ℹ️",
    )

    user_question = st.text_input(
        "Ask your first-aid question (Arabic or English):",
        placeholder="e.g. What should I do for a burn? / ماذا أفعل في حالة الحرق؟",
    )

    if st.button("Get Answer", type="primary") and user_question.strip():

        with st.spinner("Retrieving relevant evidence..."):
            context = retrieve_context_module.retrieve_context(
                user_question=user_question,
                tfidf_vectorizer=resources["tfidf_vectorizer"],
                tfidf_matrix=resources["tfidf_matrix"],
                bm25=resources["bm25"],
                embedding_model=resources["embedding_model"],
                embedding_matrix=resources["embedding_matrix"],
                chunks_df=resources["chunks_df"],
            )

        with st.spinner("Generating grounded answer..."):
            result = prompting_module.generate_grounded_answer(user_question, context)

        st.subheader("📌 English Answer")
        st.markdown(result["english_answer"])

        st.subheader("📌 الإجابة بالعربية")
        st.markdown(result["arabic_answer"])

        grounding = result["grounding"]
        st.divider()
        st.subheader("🔍 Grounding Report")
        st.write(f"Retrieved sources: {grounding['num_sources']}")
        st.write(f"Top rerank score: {grounding['top_score']:.3f}")

        if not grounding["grounded_sources"].empty:
            st.dataframe(grounding["grounded_sources"], use_container_width=True)

    elif user_question.strip() == "":
        st.info("Type a first-aid question above and press **Get Answer**.")


if __name__ == "__main__":
    main()
